jQuery(document).ready(function(){jQuery("html").bind("click",function(e){jQuery('.dropdown-toggle, a.menu').parent("li").removeClass("open");});jQuery(".dropdown-toggle, a.menu").click(function(e){if(jQuery(this).parent("li").hasClass("open")){jQuery("ul").find('li').removeClass('open');}
else{jQuery("ul").find('li').removeClass('open');jQuery(this).parent("li").addClass('open');}
return false;});jQuery(".tab_content").hide();jQuery("#tabs ul.tabs li:first").addClass("active").show();jQuery(".tab_content:first").show();jQuery("#tabs ul.tabs li").click(function(){jQuery("ul").find('li').removeClass('open');jQuery("ul.tabs li").removeClass("active");jQuery(this).addClass("active");var activeTab=jQuery(this).find("a").attr("href");if(activeTab.substr(0,1)=="#"&&activeTab.substr(1)!=""){jQuery(".tab_content").hide();jQuery(activeTab).fadeIn();return false;}else{return true;}});});function toggleCheckboxes(classname){jQuery("."+classname).attr('checked',!jQuery("."+classname+":first").is(':checked'));}
function disableFields(classname,disable){if(disable)jQuery("."+classname).attr("disabled","disabled");else jQuery("."+classname).removeAttr("disabled");}
function popupWindow(addr,popname,w,h,features){var winl=(screen.width-w)/2;var wint=(screen.height-h)/2;if(winl<0)winl=0;if(wint<0)wint=0;var settings='height='+h+',';settings+='width='+w+',';settings+='top='+wint+',';settings+='left='+winl+',';settings+=features;win=window.open(addr,popname,settings);win.window.focus();}
function extraTicketAttachment(){jQuery("#fileuploads").append('<input type="file" name="attachments[]" style="width:70%;" /><br />');}
function rating_hover(id){var selrating=id.split('_');for(var i=1;i<=5;i++){if(i<=selrating[1])document.getElementById(selrating[0]+'_'+i).style.background="url(images/rating_pos.png)";if(i>selrating[1])document.getElementById(selrating[0]+'_'+i).style.background="url(images/rating_neg.png)";}}
function rating_leave(id){for(var i=1;i<=5;i++){document.getElementById(id+'_'+i).style.background="url(images/rating_neg.png)";}}
function rating_select(tid,c,id){window.location='viewticket.php?tid='+tid+'&c='+c+'&rating='+id;}
function limitchange(){jQuery("#itemlim").val(jQuery("#itemlimit").val());jQuery("#itemlimfrm").submit();}